graph TD;
    A[Start] --> B[handleJobEvent]
    B --> C{Is job active?}
    C -- Yes --> D[Execute job]
    D --> E{Job response status}
    E -- 200 --> F[handleSuccessCase]
    E -- 504 --> G[Get job meta]
    G --> H[Save job]
    H --> I[Schedule fix interval task]
    E -- Other --> J[handleErrorResponse]
    C -- No --> K[Remove scheduled task]
    F --> L[Update job schedule time]
    J --> L
    L --> M[Log job details]
    K --> M
    M --> N[End]

    
